version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install git wget zip libssl-dev -y
      - wget --quiet https://github.com/gohugoio/hugo/releases/download/v0.126.1/hugo_extended_0.126.1_linux-amd64.deb
      - apt install ./hugo_extended_0.126.1_linux-amd64.deb
      - rm ./hugo_extended_0.126.1_linux-amd64.deb
      - hugo env
      - wget https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-x86_64-unknown-linux-musl.tar.gz
      - tar -xvzf pagefind_extended-v1.1.0-x86_64-unknown-linux-musl.tar.gz 
      - rm pagefind_extended-v1.1.0-x86_64-unknown-linux-musl.tar.gz 
      - rm -fr themes/hugo-coder
      - ./pagefind_extended --version
      - git clone --depth 1 https://github.com/luizdepra/hugo-coder.git themes/hugo-coder
  build:
    commands:
      - export GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export GIT_COMMIT_SHA_SHORT=$(echo $GIT_COMMIT_SHA | cut -c '-6')
      - hugo
      - >
        mkdir -pv /tmp/hugo/min
        find ./publ/css/ -type f -name '*.css' -exec sh -c '
          for css_file; do
            echo "purify $css_file"
            purifycss "$css_file" "./public/**/*.html" --out "/tmp/hugo/min/$(basename $css_file)" -m -i
            mv -v "/tmp/hugo/min/$(basename $css_file)" "$css_file"
          done
        ' sh {} +
        rm -fr /tmp/hugo/min
      - ./pagefind_extended --site ./public
  post_build:
    commands:
artifacts:
  # https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
  files:
    - '**/*'
  base-directory: public
