baseURL = "https://g4s8.wtf"
languageCode = "en-us"
title = "Kirill Che."
theme = "hugo-coder"
defaultcontentlanguage = "en"

enableRobotsTXT = true

[params]
    author = "Kirill Che."
    description = "Kirill Che. personal website"
    info = "Website about Go, distributed systems, high-load"
    avatarurl = "https://avatars0.githubusercontent.com/u/1524988?s=460&v=4"

    dateformat = "January 2, 2006"

    rtl = false
    hideColorSchemeToggle = true
    # Use inverted colors
    inverted = false
    hideCredits = true
    hideCopyright = false

    since = 2020
    commit = "https://github.com/g4s8/g4s8.wtf/commit/"

    # Series see also post count
    maxSeeAlsoItems = 5

    customJS = ["js/custom.js"]
    enableRobotsTXT = true

    license = """ \
     <div xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/" style="display: inline-block;"> \
       <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0 \
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1">\
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1">\
       </a> \
       (\
       <a property="dct:title" rel="cc:attributionURL" href="https://g4s8.wtf">g4s8.wtf</a> \
       by \
       <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://g4s8.wtf/about">Kirill Che.</a>\
       )\
     </div>\
     <br/>\
    """

[params.clicky]
  id = "101432902"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"
[[menu.main]]
  name = "CV"
  weight = 3
  url = "cv-3.pdf"
[[menu.main]]
  name = "Talks"
  weight = 4
  url = "talks/"
[[menu.main]]
  name = "Research"
  weight = 5
  url = "research/"
[[menu.main]]
  name = "Contact me"
  weight = 6
  url = "about/#contact-me"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/g4s8/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/kiryll_che"
[[params.social]]
    name = "Stackoverflow"
    icon = "fa fa-stack-overflow fa-2x"
    weight = 3
    url = "https://stackoverflow.com/users/1723695"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram fa-2x"
    wight = 4
    url = "https://t.me/g4s8_chan"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    wight = 5
    url = "https://www.linkedin.com/in/kirill-che"

[params.csp]
  childsrc = ["'self'"]
  fontsrc = [
    "'self'",
  ]
  formaction = ["'self'"]
  framesrc = [
    "'self'"
  ]
  imgsrc = [
    "'self'",
    "data:",
    "https://avatars0.githubusercontent.com",
    "https://licensebuttons.net",
    "https://mirrors.creativecommons.org"
  ]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'"
  ]
  scriptsrc = [
    "'self'",
    "https://static.getclicky.com",
    "https://in.getclicky.com",
    "'unsafe-eval'",
    "'unsafe-inline'"
  ]
  connectsrc = [
    "'self'",
    "https://files.stork-search.net",
    "https://in.getclicky.com"
  ]

[deployment]
order = [".jpg$", ".gif$"]

[security]
  [security.funcs]
    getenv = ["GIT_COMMIT_SHA", "GIT_COMMIT_SHA_SHORT"]
