[input]
base_directory = "content/posts"
url_prefix = "/posts/"


[[input.files]]
path = "enum-is-object.md"
url = "enum-is-object"
title = "Enum: object or global variable (Java)"

[[input.files]]
path = "rx-misundarstandings.md"
url = "rx-misundarstandings"
title = "Four misunderstandings of reactive streams"

[[input.files]]
path = "github-hooks-app.md"
url = "github-hooks-app"
title = "Step by step guide for creating GitHub hooks App"

[[input.files]]
path = "go-low-latency-1.md"
url = "go-low-latency-one"
title = "Go low latency patterns (I)"

[[input.files]]
path = "go-low-latency-2.md"
url = "go-low-latency-two"
title = "Go low latency patterns (II)"

[[input.files]]
path = "go-errors.md"
url = "go-errors-performance"
title = "The performance of Go error handling"

[output]
filename = "static/stork.st"
